「Rails の i18n を理解する」の答案提出
kaisumi/fjord-books_app pull request #1
Opened 2021-12-21 02:05 UTC by kaisumi

お世話になっております。
「Rails の i18n を理解する」の答案を提出します。
ご確認をよろしくお願いします。

2021-12-26 14:34 UTC, u1tnk requested changes
プラクティスに書いている

> human_attribute_nameやmodel_name.humanを使うようにしてみましょう。

が対応されてないので、確認してください。

また、トップにdictionaryと付けているようですが、自作部分のトップという意味しか無いと思うので、意味のある名前にしましょう。

book独自のものだったらbooks以下にしたり、共通の遷移メッセージだったらviews以下とか…commonとかでも良いですね。

2021-12-27 02:26 UTC, kaisumi commented
コメントいただきありがとうございました。
対応漏れがあり、申し訳ありませんでした。
human_attribute_name、model_name.humanに対応しました。
訳語を適切に分類しました。
ご確認をよろしくお願いいたします。

2021-12-29 06:56 UTC, u1tnk requested changes
もうちょっとだけ修正お願いします 🙏

2021-12-29 06:56 UTC, u1tnk commented on app/views/books/_form.html.erb
> +    <%= form.label Book.human_attribute_name('title') %>
どっちでも良いのですが、シンボルで文字列でも良いときは `'title'`と文字列よりも `:title` とシンボルで書く方がスッキリしますね。 Railsガイドでは文字列ですし、どっちでも良いのですが参考まで。

2021-12-29 06:56 UTC, u1tnk commented on app/controllers/books_controller.rb
> +        format.html { redirect_to @book, notice: Book.human_attribute_name('notice.successful_book_creation') }
属性名は human_attribute_nameを使いますが、このメッセージの場合は 
`t 'books.successful_creation'`の方がスッキリしますね。そもそもこのメッセージのキーが `attributes`以下にあるのはおかしいので修正お願いします。

モデル名、属性名は human系を使いますが、その他は tで済ますのが一般的です。

2022-01-03 00:20 UTC, kaisumi commented on app/views/books/_form.html.erb
> +    <%= form.label Book.human_attribute_name('title') %>
コメントありがとうございます！
修正しました。

2022-01-03 00:20 UTC, kaisumi commented on app/controllers/books_controller.rb
> +        format.html { redirect_to @book, notice: Book.human_attribute_name('notice.successful_book_creation') }
コメントありがとうございます！
修正しました。

2022-01-03 02:39 UTC, u1tnk approved these changes

2022-01-04 01:05 UTC, merged