「Railsでユーザーフォローを作る」答案提出
kaisumi/fjord-books_app pull request #5
Opened 2021-12-24 05:50 UTC by kaisumi

お世話になっております。
「Railsでユーザーフォローを作る」の答案を提出いたします。
ご確認をよろしくお願いいたします。

2021-12-29 06:48 UTC, komagata commented on app/controllers/followers_controller.rb
> +    @followers = \
`\`はなくても大丈夫だった気がします〜

2022-01-03 05:49 UTC, kaisumi commented on app/controllers/followers_controller.rb
> +    @followers = \
削除しました！

2022-01-03 05:50 UTC, kaisumi commented
コメントありがとうございます。
データベースをリセットしてテストするとFollowerIDがない場合にエラーが出たので、その部分も併せて修正しました。
ご確認をよろしくお願いいたします。

2022-01-04 04:17 UTC, komagata requested changes

2022-01-04 04:17 UTC, komagata commented on app/helpers/follows_helper.rb
> +    (Follow.find_by(user_id: params[:id], follower_id: follower.id).nil? ? false : true) unless follower.nil?
```suggestion
    !Follow.exists?(user_id: params[:id], follower_id: follower.id) if follower
```

こんな感じでいいかも？

2022-01-04 04:17 UTC, komagata commented on db/schema.rb
> +  create_table "followers", force: :cascade do |t|
railsから離れてDB設計を考えてみてください。
userのフォロー関係はUsersテーブルと関連テーブル一つで表現できると思います。
「自己参照する多対多」の関係です。これをググるといろいろ出てくるかもです〜。

2022-01-10 05:52 UTC, kaisumi commented on app/helpers/follows_helper.rb
> +    (Follow.find_by(user_id: params[:id], follower_id: follower.id).nil? ? false : true) unless follower.nil?
ありがとうございます！
修正しました。

2022-01-10 05:52 UTC, kaisumi commented on db/schema.rb
> +  create_table "followers", force: :cascade do |t|
コメントありがとうございます！とても勉強になりました。
修正しました。

2022-01-11 04:37 UTC, komagata requested changes

2022-01-11 04:37 UTC, komagata commented on app/controllers/follows_controller.rb
> +  def show_followers
[Railsでユーザーフォローを作る | FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/170)

こちらの「参考」のページを参照して、ControllerにCRUD以外のアクションを作らないように分割を検討してみてください〜

2022-01-12 02:34 UTC, kaisumi commented on app/controllers/follows_controller.rb
> +  def show_followers
コメントありがとうございます！モデルでコントローラ1つにしていたところをFollowerとFollowingでコントローラを分けました。またルーティングがリソースフルではなかったので、修正しました。

2022-01-13 06:37 UTC, komagata requested changes

2022-01-13 06:37 UTC, komagata commented on app/controllers/followings_controller.rb
> +    @follows = Kaminari.paginate_array(@follows).page(params[:page])
paginate_arrayではなく、普通のkaminariのpagingを使った方がいいかもです〜

2022-01-13 06:37 UTC, komagata commented on app/helpers/follows_helper.rb
> +  def follower?
暗黙的に必要としているデータが多い（current_userがあることが前提なのと、Userのidがparams[:id]としてそのページにあることが前提）ので、使っている場所を見た人にとっては、このメソッドがどういうことをやってるのか分かりづらいかもです。

2022-01-14 00:48 UTC, kaisumi commented on app/controllers/followings_controller.rb
> +    @follows = Kaminari.paginate_array(@follows).page(params[:page])
コメントありがとうございます！修正しました。

2022-01-14 00:49 UTC, kaisumi commented on app/helpers/follows_helper.rb
> +  def follower?
コメントありがとうございます！わかりづらいですね。修正しましたm(_ _)m

2022-01-14 02:41 UTC, komagata commented on app/helpers/follows_helper.rb
> +  def follower?(follower_id:, following_id:)
View以外でも使えそうな機能なのでUserのメソッドにすると引数が減ってわかりやすいかもです〜

2022-01-14 07:59 UTC, kaisumi commented on app/helpers/follows_helper.rb
> +  def follower?(follower_id:, following_id:)
コメントありがとうございます！Userのメソッドにして`current_user.following?(@user)`で使用できるようにしました。

2022-01-14 09:00 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2022-01-14 14:53 UTC, merged