「omniauth を使って GitHub 認証を実装する」答案提出
kaisumi/fjord-books_app pull request #7
Opened 2022-01-18 13:25 UTC by kaisumi

お世話になっております。
「omniauth を使って GitHub 認証を実装する」の答案を提出いたします。
ご確認をよろしくお願いいたします。

2022-01-23 13:19 UTC, u1tnk requested changes
概ね大丈夫ですが、細かいところいくつかコメントしていますのでご確認ください。

2022-01-23 13:19 UTC, u1tnk commented on app/controllers/users/registrations_controller.rb
> +  # before_action :configure_sign_up_params, only: [:create]
コメントアウトが大量にあると見づらいので削除して欲しいです。

2022-01-23 13:19 UTC, u1tnk commented on Gemfile
> +gem 'omniauth-github', github: 'omniauth/omniauth-github', branch: 'master'
こちら `gem 'omniauth-github' だけで良いと思うのですが、何故ブランチ指定してるのでしょうか？

2022-01-23 13:19 UTC, u1tnk commented on Gemfile
> +gem 'omniauth-rails_csrf_protection'
こちらはあっても問題無いですが、必要でも無いと思うのですが、何故追加したのでしょうか？

2022-01-23 13:19 UTC, u1tnk commented on config/initializers/devise.rb
> +  config.omniauth :github, ENV['GITHUB_KEY'], ENV['GITHUB_SECRET'], scope: 'read:user'
必須では無いですが、環境変数が必要になるので READMEなどに設定方法を書いておくと良いですね。

2022-01-25 23:04 UTC, kaisumi commented on app/controllers/users/registrations_controller.rb
> +  # before_action :configure_sign_up_params, only: [:create]
コメントありがとうございます。削除しました。

2022-01-25 23:10 UTC, kaisumi commented on Gemfile
> +gem 'omniauth-rails_csrf_protection'
[DeviseのWiki](https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview)に以下のように記載があったため、追加してあります。
> OmniAuth 2.0+: make sure you also add the [OmniAuth Rails CSRF Protection](https://github.com/cookpad/omniauth-rails_csrf_protection) gem to your `Gemfile`

機能上は不要だと思いますが、セキュリティ上、CSRF攻撃を防ぐために必要なものだと思っていました。GitHub認証では不要なのでしょうか？

2022-01-25 23:10 UTC, kaisumi commented on config/initializers/devise.rb
> +  config.omniauth :github, ENV['GITHUB_KEY'], ENV['GITHUB_SECRET'], scope: 'read:user'
コメントありがとうございます。READMEに追記しました。

2022-01-26 00:20 UTC, kaisumi commented on Gemfile
> +gem 'omniauth-github', github: 'omniauth/omniauth-github', branch: 'master'
おっしゃる通りブランチ指定はいらないですね。削除しました。
![image](https://user-images.githubusercontent.com/39044468/151081735-fa3a2c64-82d8-4a5a-bee4-5c8287271f43.png)

2022-01-26 05:53 UTC, u1tnk commented on Gemfile
> +gem 'omniauth-rails_csrf_protection'
なるほど。 Deviseのwikiに書いてあったなら根拠としては十分ですね。

同じ問題について https://github.com/omniauth/omniauth/issues/960 
omniauth側でも対応してるようなのですが、まったく同じ内容なのか分かりません。時期からして omniauthの問題なら対応していそうなものですが 🤔 
ちょっと他のメンターにも聞いてみます。
プラクティスとしては十分な根拠があって追加しているので問題無いです 🙆‍♀️

2022-01-26 05:53 UTC, u1tnk approved these changes

2022-01-26 06:06 UTC, u1tnk commented on Gemfile
> +gem 'omniauth-rails_csrf_protection'
https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284

こちらに omniauth 側の説明もありましたね。問題無さそうです 👍

2022-01-26 07:31 UTC, kaisumi commented on Gemfile
> +gem 'omniauth-rails_csrf_protection'
ご確認ありがとうございます 😄 勉強になりました 🧑‍🎓

2022-01-26 07:31 UTC, merged